# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pk2jN4AGFNqHHbJjEUAWlhh_yIKJYAmQ
"""

import streamlit as st
import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from PIL import Image
from io import BytesIO

# -------------------- PAGE CONFIG --------------------
st.set_page_config(
    page_title="Airbnb AI System",
    layout="wide",
    page_icon="🏡"
)

# -------------------- CUSTOM STYLE --------------------
st.markdown("""
    <style>
    .main {
        background-color: #f7f9fc;
    }
    h1 {
        color: #ff5a5f;
    }
    .stMetric {
        background-color: #ffffff;
        padding: 10px;
        border-radius: 10px;
        box-shadow: 0px 2px 6px rgba(0,0,0,0.05);
    }
    </style>
""", unsafe_allow_html=True)

# -------------------- LOAD DATA --------------------
@st.cache_data
def load_data():
    df = pd.read_csv("dublin_aggregated_df(1).csv")
    raw_df = pd.read_csv("dublin_merged_df(1).csv.gz", compression="gzip")
    raw_df["date"] = pd.to_datetime(raw_df["date"])
    raw_df["month"] = raw_df["date"].dt.month
    return df, raw_df

@st.cache_resource
def load_models():
    price_model = joblib.load("xgb_model_log(1).pkl")
    rec_model = joblib.load("svd_model.pkl")
    return price_model, rec_model

df, raw_df = load_data()
price_model, rec_model = load_models()

# -------------------- HEADER --------------------
st.title("🏡 Airbnb AI System")
st.markdown("### Price Prediction + Recommendation System")

# -------------------- KPI METRICS --------------------
col1, col2, col3 = st.columns(3)

col1.metric("📊 Avg Price", f"€{round(df['price'].mean(), 2)}")
col2.metric("⭐ Avg Rating", round(df['review_scores_rating'].mean(), 2))
col3.metric("🏘️ Listings", len(df))

# -------------------- MAIN TABS --------------------
tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "📊 Dashboard",
    "📈 Visual Insights",
    "🧠 Model Insights",
    "🤖 Price Prediction",
    "🎯 Recommendations"
])

# -------------------- TAB 1 --------------------
with tab1:
    st.subheader("Dataset Overview")
    st.dataframe(df, use_container_width=True)

# -------------------- TAB 2 --------------------
with tab2:
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Price vs Rating")
        st.scatter_chart(df, x="price", y="review_scores_rating")

        top_types = raw_df["property_type"].value_counts().nlargest(10).index
        pt_data = raw_df[raw_df["property_type"].isin(top_types)] \
            .groupby("property_type")["price"].mean().reset_index()

        st.subheader("Top Property Types")
        st.bar_chart(pt_data, x="property_type", y="price")

    with col2:
        st.subheader("Price Distribution")
        fig, ax = plt.subplots()
        ax.hist(df["price"], bins=20)
        st.pyplot(fig)

        monthly = raw_df.groupby("month")["price"].mean().reset_index()
        monthly["month"] = pd.to_datetime(monthly["month"], format="%m").dt.strftime("%B")

        st.subheader("Monthly Trends")
        st.line_chart(monthly, x="month", y="price")

    st.subheader("Geographical Distribution")
    st.map(raw_df.sample(1000), latitude="latitude", longitude="longitude")

# -------------------- ENCODING --------------------
@st.cache_data
def calculate_frequency_encodings(neighbourhood, property_type, df):
    n_freq = df[df["neighbourhood"] == neighbourhood]["neighbourhood_freq"].mean()
    p_freq = df[df["property_type"] == property_type]["property_type_freq"].mean()

    if pd.isna(n_freq):
        n_freq = df["neighbourhood_freq"].mean()
    if pd.isna(p_freq):
        p_freq = df["property_type_freq"].mean()

    return n_freq, p_freq

# -------------------- TAB 3 --------------------
with tab3:
    st.subheader("Model Insights")

    # -------- XGBOOST METRICS --------
    st.markdown("### 📊 Price Prediction Model Performance (XGBoost)")
    st.success("""
    R² Score: 0.6925
    Test RMSE (log-scale): 0.3910
    Test MAE (log-scale): 0.2665
    """)

    # -------- FEATURE IMPORTANCE --------
    if hasattr(price_model, "named_steps"):
        model_step = price_model.named_steps.get("xgb", price_model)
    else:
        model_step = price_model

    if hasattr(model_step, "feature_importances_"):

        feature_names = [
            'host_response_rate','host_is_superhost','host_listings_count',
            'accommodates','bedrooms','beds',
            'review_scores_rating','number_of_reviews',
            'review_scores_cleanliness','review_scores_location',
            'maximum_nights','neighbourhood_freq','property_type_freq'
        ]

        fi = pd.DataFrame({
            "Feature": feature_names,
            "Importance": model_step.feature_importances_
        }).sort_values(by="Importance", ascending=True)

        fig, ax = plt.subplots()
        ax.barh(fi["Feature"], fi["Importance"])
        ax.set_title("Feature Importance")
        st.pyplot(fig)

    # -------- RECOMMENDER METRICS --------
    st.markdown("### 🎯 Recommendation Model Performance (SVD)")
    st.info("""
    RMSE: 0.424
    MAE: 0.310
    """)

# -------------------- TAB 4 (PREDICTION) --------------------
with tab4:
    st.subheader("Enter Property Details")

    col1, col2 = st.columns(2)

    with col1:
        host_response_rate = st.slider("Response Rate", 0.0, 1.0, 0.9)
        host_is_superhost = st.selectbox("Superhost", ["yes", "no"])
        host_listings_count = st.number_input("Listings Count", 1, 100, 1)

    with col2:
        property_type = st.selectbox("Property Type", df["property_type"].dropna().unique())
        accommodates = st.slider("Accommodates", 1, 20, 2)
        bedrooms = st.slider("Bedrooms", 0, 10, 1)
        beds = st.slider("Beds", 1, 20, 1)

    neighbourhood = st.selectbox("Neighbourhood", df["neighbourhood"].dropna().unique())

    col3, col4 = st.columns(2)
    with col3:
        rating = st.slider("Rating", 0.0, 5.0, 4.5)
        cleanliness = st.slider("Cleanliness", 0.0, 5.0, 4.5)
    with col4:
        location = st.slider("Location Score", 0.0, 5.0, 4.5)
        reviews = st.number_input("Number of Reviews", 0, 500000, 10)

    max_nights = st.slider("Max Nights", 1, 1125, 30)

    if st.button("🚀 Predict Price"):

        n_freq, p_freq = calculate_frequency_encodings(neighbourhood, property_type, df)

        input_df = pd.DataFrame([{
            'host_response_rate': host_response_rate,
            'host_is_superhost': 1 if host_is_superhost == "yes" else 0,
            'host_listings_count': host_listings_count,
            'accommodates': accommodates,
            'bedrooms': bedrooms,
            'beds': beds,
            'maximum_nights': max_nights,
            'review_scores_rating': rating,
            'review_scores_cleanliness': cleanliness,
            'review_scores_location': location,
            'number_of_reviews': reviews,
            'neighbourhood_freq': n_freq,
            'property_type_freq': p_freq
        }])

        try:
            input_df = input_df[price_model.feature_names_in_]
        except:
            pass

        pred_log = price_model.predict(input_df)
        price = np.exp(pred_log[0])

        st.success(f"💰 Estimated Price: €{round(price, 2)}")
        st.metric("Predicted Price (€)", round(price, 2))
        st.info(f"Range: €{round(price*0.85,2)} - €{round(price*1.15,2)}")

# -------------------- TAB 5 (RECOMMENDATION) --------------------
with tab5:
    st.subheader("Personalized Airbnb Recommendations")

    user_id = st.number_input("Enter User ID", min_value=1, value=1412033)

    def recommend_airbnbs(user_id, listings_df, model):

        user_listings = listings_df[listings_df["reviewer_id"] == user_id]["id_x"].unique()
        all_listings = listings_df["id_x"].unique()

        listings_to_predict = list(set(all_listings) - set(user_listings))
        pairs = [(user_id, lid, 0) for lid in listings_to_predict]

        predictions = model.test(pairs)
        top_5 = sorted(predictions, key=lambda x: x.est, reverse=True)[:5]

        for idx, rec in enumerate(top_5, 1):
            listing = listings_df[listings_df["id_x"] == rec.iid].iloc[0]

            st.markdown(f"### #{idx} {listing['name']}")

            col1, col2 = st.columns([2,1])

            with col1:
                st.write(listing["description"])
                st.write(f"💰 €{listing['price']} | 📍 {listing['neighbourhood']}")
                st.write(f"⭐ {listing['avg_rating']} ({listing['number_of_reviews']} reviews)")

                if st.button(f"View Listing {idx}", key=idx):
                    try:
                        response = requests.get(listing["picture_url"])
                        img = Image.open(BytesIO(response.content))
                        st.image(img)
                        st.markdown(f"[Open Listing]({listing['listing_url']})")
                    except:
                        st.error("Image failed")

            with col2:
                try:
                    response = requests.get(listing["picture_url"])
                    img = Image.open(BytesIO(response.content))
                    st.image(img)
                except:
                    st.warning("No image")

            st.divider()

    if st.button("Get Recommendations"):
        recommend_airbnbs(user_id, raw_df, rec_model)
